FROM node:14-alpine3.12

WORKDIR /app

COPY . .

RUN npm install -g nodemon 

HEALTHCHECK --interval=60s --timeout=2s --retries=3 CMD wget localhost:5000/api/ -q -O - > /dev/null 2>&1

CMD [ "npm","run","dev"]

EXPOSE 5000